[[redirects]]
  from = "/asset-proxy/*"
  to = ".netlify/functions/assets/:splat"
  status = 302

[build]
 command = "npm run build"
 functions = "functions"

 [build.environment]
    NODE_VERSION = "12"