[[redirects]]
  from = "/asset-proxy/*"
  to = "https://api.netlify.com/api/v1/sites/ae146f89-c18b-46ea-9f03-967c2203b17d/assets/:splat"
  status = 200
  force = true
  headers = { Authorization = "Bearer NETLIFY_API_TOKEN"}
  conditions = {Role = ["admin"]}

[build]
 command = "npm run build"